define({
	STAIR_SMOOTHING: 0.8,
	PLAYER_HEIGHT: 60,
	EXTRA_SPEED_DECAY: 0.05,
	CAMERA_HEIGHT: 40,
	CAMERA_FOV: 3.14/2*0.8,
	CAMERA_BOB_AMOUNT: 3,
	CAMERA_BOB_CYCLE: 4,

	F_SOLID: 1,
	F_DYNAMIC: 2,
	F_PLAYER: 4,
});
